version: "3"
services:
  localstack:
    image: localstack/localstack:0.12.1
    container_name: localstack
    ports:
      - 127.0.0.1:4566:4566
    environment:
      - DEBUG=1
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=false
      - LAMBDA_REMOTE_DOCKER=true
      - SERVICES=lambda
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/tmp/localstack

volumes:
  localstack_data:
